
server:
  port: 80
spring:

  application:
    name: blog
    #数据库的配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #redis配置

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      #一次上传文件的最大总量
      max-request-size: 50MB
      #单个文件的最大值
      max-file-size: 50MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印日志
  global-config:
    db-config:
      table-prefix: ms_             #表的前缀

